"""Add processing_stage field

Revision ID: 571e3c813ac6
Revises: a3502ff8981c
Create Date: 2025-07-16 08:42:41.494698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '571e3c813ac6'
down_revision: Union[str, Sequence[str], None] = 'a3502ff8981c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('processing_stage', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'processing_stage')
    # ### end Alembic commands ###
