"""Initial schema with videos and jobs tables

Revision ID: a3502ff8981c
Revises: 
Create Date: 2025-07-15 00:57:39.464134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3502ff8981c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('insights', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('uploader', sa.String(length=255), nullable=True),
    sa.Column('channel', sa.String(length=255), nullable=True),
    sa.Column('channel_id', sa.String(length=255), nullable=True),
    sa.Column('uploader_id', sa.String(length=255), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('subscriber_count', sa.Integer(), nullable=True),
    sa.Column('upload_date', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('release_timestamp', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('video_id', sa.String(length=255), nullable=True),
    sa.Column('webpage_url', sa.String(length=2048), nullable=True),
    sa.Column('original_url', sa.String(length=2048), nullable=True),
    sa.Column('extractor', sa.String(length=100), nullable=True),
    sa.Column('extractor_key', sa.String(length=100), nullable=True),
    sa.Column('resolution', sa.String(length=50), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Integer(), nullable=True),
    sa.Column('vcodec', sa.String(length=100), nullable=True),
    sa.Column('acodec', sa.String(length=100), nullable=True),
    sa.Column('filesize', sa.Integer(), nullable=True),
    sa.Column('filesize_approx', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('subtitles', sa.JSON(), nullable=True),
    sa.Column('automatic_captions', sa.JSON(), nullable=True),
    sa.Column('age_limit', sa.Integer(), nullable=True),
    sa.Column('availability', sa.String(length=50), nullable=True),
    sa.Column('live_status', sa.String(length=50), nullable=True),
    sa.Column('was_live', sa.Boolean(), nullable=True),
    sa.Column('playable_in_embed', sa.Boolean(), nullable=True),
    sa.Column('thumbnail', sa.String(length=2048), nullable=True),
    sa.Column('thumbnails', sa.JSON(), nullable=True),
    sa.Column('playlist', sa.String(length=255), nullable=True),
    sa.Column('playlist_id', sa.String(length=255), nullable=True),
    sa.Column('playlist_title', sa.String(length=500), nullable=True),
    sa.Column('playlist_index', sa.Integer(), nullable=True),
    sa.Column('playlist_count', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('abr', sa.Integer(), nullable=True),
    sa.Column('vbr', sa.Integer(), nullable=True),
    sa.Column('tbr', sa.Integer(), nullable=True),
    sa.Column('channel_follower_count', sa.Integer(), nullable=True),
    sa.Column('chapters', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('progress', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    op.drop_table('videos')
    # ### end Alembic commands ###
